name: vancouver-hvi
channels:
  - conda-forge
dependencies:
  - python=3.11
  - geopandas
  - pyogrio
  - shapely
  - fiona
  - rasterio
  - rtree
  - pyproj
  - pandas
  - numpy
  - matplotlib
  - tqdm
  - jupyterlab
  - pip
  - pip:
      - mapclassify
      - python-dotenv
